[2025-10-17T21:04:37.462+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_seed manual__2025-10-17T21:04:34.513140+00:00 [queued]>
[2025-10-17T21:04:37.470+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_seed manual__2025-10-17T21:04:34.513140+00:00 [queued]>
[2025-10-17T21:04:37.471+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:04:37.483+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_seed> on 2025-10-17 21:04:34.513140+00:00
[2025-10-17T21:04:37.487+0000] {standard_task_runner.py:57} INFO - Started process 232 to run task
[2025-10-17T21:04:37.491+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_seed', 'manual__2025-10-17T21:04:34.513140+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmplnzpqcbu']
[2025-10-17T21:04:37.494+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask dbt_seed
[2025-10-17T21:04:37.513+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:04:37.553+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_seed manual__2025-10-17T21:04:34.513140+00:00 [running]> on host b0360591ae5e
[2025-10-17T21:04:37.628+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_seed' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T21:04:34.513140+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T21:04:34.513140+00:00'
[2025-10-17T21:04:37.629+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:04:37.630+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt seed --profiles-dir /opt/***/dbt']
[2025-10-17T21:04:37.639+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:04:40.790+0000] {subprocess.py:93} INFO - [0m21:04:40  Running with dbt=1.7.0
[2025-10-17T21:04:41.227+0000] {subprocess.py:93} INFO - [0m21:04:41  Registered adapter: postgres=1.7.0
[2025-10-17T21:04:41.302+0000] {subprocess.py:93} INFO - [0m21:04:41  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-10-17T21:04:41.305+0000] {subprocess.py:93} INFO - [0m21:04:41
[2025-10-17T21:04:41.430+0000] {subprocess.py:93} INFO - [0m21:04:41  Concurrency: 1 threads (target='dev')
[2025-10-17T21:04:41.431+0000] {subprocess.py:93} INFO - [0m21:04:41
[2025-10-17T21:04:41.441+0000] {subprocess.py:93} INFO - [0m21:04:41  1 of 1 START seed file public.raw_data ......................................... [RUN]
[2025-10-17T21:04:41.561+0000] {subprocess.py:93} INFO - [0m21:04:41  1 of 1 OK loaded seed file public.raw_data ..................................... [[32mINSERT 3[0m in 0.12s]
[2025-10-17T21:04:41.580+0000] {subprocess.py:93} INFO - [0m21:04:41
[2025-10-17T21:04:41.581+0000] {subprocess.py:93} INFO - [0m21:04:41  Finished running 1 seed in 0 hours 0 minutes and 0.27 seconds (0.27s).
[2025-10-17T21:04:41.598+0000] {subprocess.py:93} INFO - [0m21:04:41
[2025-10-17T21:04:41.599+0000] {subprocess.py:93} INFO - [0m21:04:41  [32mCompleted successfully[0m
[2025-10-17T21:04:41.600+0000] {subprocess.py:93} INFO - [0m21:04:41
[2025-10-17T21:04:41.601+0000] {subprocess.py:93} INFO - [0m21:04:41  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-10-17T21:04:42.459+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:04:42.487+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_seed, execution_date=20251017T210434, start_date=20251017T210437, end_date=20251017T210442
[2025-10-17T21:04:42.509+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:04:42.537+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
