[2025-10-17T21:17:13.523+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_seed manual__2025-10-17T21:17:05.130390+00:00 [queued]>
[2025-10-17T21:17:13.531+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_seed manual__2025-10-17T21:17:05.130390+00:00 [queued]>
[2025-10-17T21:17:13.532+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:17:13.543+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_seed> on 2025-10-17 21:17:05.130390+00:00
[2025-10-17T21:17:13.548+0000] {standard_task_runner.py:57} INFO - Started process 194 to run task
[2025-10-17T21:17:13.551+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_seed', 'manual__2025-10-17T21:17:05.130390+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpoj_u1j3f']
[2025-10-17T21:17:13.554+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask dbt_seed
[2025-10-17T21:17:13.570+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:17:13.607+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_seed manual__2025-10-17T21:17:05.130390+00:00 [running]> on host 10529ec04042
[2025-10-17T21:17:13.679+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_seed' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T21:17:05.130390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T21:17:05.130390+00:00'
[2025-10-17T21:17:13.681+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:17:13.682+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt seed --profiles-dir /opt/***/dbt']
[2025-10-17T21:17:13.690+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:17:16.321+0000] {subprocess.py:93} INFO - [0m21:17:16  Running with dbt=1.7.0
[2025-10-17T21:17:16.659+0000] {subprocess.py:93} INFO - [0m21:17:16  Registered adapter: postgres=1.7.0
[2025-10-17T21:17:16.740+0000] {subprocess.py:93} INFO - [0m21:17:16  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-10-17T21:17:16.745+0000] {subprocess.py:93} INFO - [0m21:17:16
[2025-10-17T21:17:16.869+0000] {subprocess.py:93} INFO - [0m21:17:16  Concurrency: 1 threads (target='dev')
[2025-10-17T21:17:16.870+0000] {subprocess.py:93} INFO - [0m21:17:16
[2025-10-17T21:17:16.879+0000] {subprocess.py:93} INFO - [0m21:17:16  1 of 1 START seed file public.raw_data ......................................... [RUN]
[2025-10-17T21:17:16.981+0000] {subprocess.py:93} INFO - [0m21:17:16  1 of 1 OK loaded seed file public.raw_data ..................................... [[32mINSERT 3[0m in 0.10s]
[2025-10-17T21:17:16.999+0000] {subprocess.py:93} INFO - [0m21:17:16
[2025-10-17T21:17:17.000+0000] {subprocess.py:93} INFO - [0m21:17:17  Finished running 1 seed in 0 hours 0 minutes and 0.25 seconds (0.25s).
[2025-10-17T21:17:17.014+0000] {subprocess.py:93} INFO - [0m21:17:17
[2025-10-17T21:17:17.015+0000] {subprocess.py:93} INFO - [0m21:17:17  [32mCompleted successfully[0m
[2025-10-17T21:17:17.016+0000] {subprocess.py:93} INFO - [0m21:17:17
[2025-10-17T21:17:17.017+0000] {subprocess.py:93} INFO - [0m21:17:17  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-10-17T21:17:17.925+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:17:17.952+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_seed, execution_date=20251017T211705, start_date=20251017T211713, end_date=20251017T211717
[2025-10-17T21:17:17.999+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:17:18.025+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
